[package]
name = "fast_add_intent"
version = "0.1.0"
authors = ["Philippe Kalitine <philippe.kalitine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "fast_add_intent"
path = "main.rs"
